{
 "title": "Bots Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Buy attempts / 5 seconds",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "index::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "bot",
     "query": "SELECT count(\"success\") FROM \"bot\" WHERE $timeFilter GROUP BY time(5s), \"index\"::tag fill(0)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buys",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT buy_timestamp, name, CONCAT(\"bot-\", LOWER(name)) AS lower_name,\r\nUNIX_TIMESTAMP(buy_timestamp - INTERVAL 1 MINUTE)*1000 AS interval_from,\r\nUNIX_TIMESTAMP(buy_timestamp + INTERVAL 10 MINUTE)*1000 AS interval_to,\r\n status, sell_transaction_hash, buy_transaction_hash, buy_chain, sell_chain FROM my_database.trades ORDER BY buy_timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Target buy amount",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "amount_update",
     "query": "SELECT target_amount, target_chain FROM \"amount_update\" GROUP BY \"index\"::tag ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "target_amount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "target_amount::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT chain_id, COUNT(*) AS available_rpcs,\r\nMIN(last_check) AS checked  FROM my_database.rpc WHERE disabled=0 AND ping>0 GROUP BY chain_id "
    }
   ]
  },
  {
   "title": "Mean duration of amount updates / 5sec",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amount_update",
     "query": "SELECT mean(\"total_seconds\") FROM \"amount_update\" WHERE $timeFilter GROUP BY time(5s), \"index\"::tag fill(null)",
     "select": [
      [
       { "params": [ "total_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}