---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mysql
  namespace: bot
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: mysql
  targetNamespace: bot
  valuesContent: |-
    persistence:
      enabled: true
    storageClass: "local-path"
    auth:
      rootPassword: "mJan2LLam"
    nodeSelector:
      kubernetes.io/hostname: master