---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: phpmyadmin
  namespace: bot-monitoring
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: phpmyadmin
  targetNamespace: bot-monitoring
  valuesContent: |-
    db:
      allowArbitraryServer: false
      port: 3306
      host: mysql.bot.svc.cluster.local
    service:
      type: LoadBalancer
      ports:
        https: 8443
        http: 8081